#+STARTUP: showall

EMACS ORG-MODE
============================================================================

Hello recruit and welcome to the Air Force where you will learn
to FLY using Org Mode.

* Mission #31: Capture

** Briefing

   On this mission you will learn how to use the capture command.

   Capture lets you quickly store notes with little interruption of your
   work flow.

** Mission

*** Using Capture:

**** Description
     
     Capture command alongside the Store Link command and the Agenda View
     command are the 'Big Three' org commands and YOU MUST configure them
     on the init.el Emacs configuration file.

     We already configure the Store Link command on mission #25, now we are
     going to configure the Capture command.

**** Keybindings

     - C-c c => Capture command.
       
**** Orders

     - Press C-x 2 to divide the frame on two windows.
       
     - Press C-x o to jump to the lower window.

     - Press C-x C-f and visit the file '~/.emacs.d/init.el'.

     - Once the 'init.el' file is opened search for the line that we
       added on mission #25:

       (global-set-key (kbd "C-c l") 'org-store-link)

       And change to the following:

       (global-set-key (kbd "C-c c") 'org-capture)
       (global-set-key (kbd "C-c l") 'org-store-link)

     - Save the file, exit Emacs, open this file again and comeback to this
       line.

     - Go to the ALPHA heading and press C-c c, this will open a buffer on
       the bottom of Emacs, this buffer asks for a template to apply to
       the capture, also this buffer will block Emacs until you do
       an action or you quit, press 'q' to quit.

     - Press C-c c again, this time we are going to use a template, on the
       Capture buffer the only available template is 'Task'.

     - Press the 't' character to select the Task template.

     - The Capture buffer will create a new TODO item with a disabled
       timestamp (remember the '[]' or '<>'), type the text: 'Follow Orders',
       then press C-c C-c, this keybinding is used to tell Capture to
       save the item. The text 'Saved ~/.notes' is displayed on the Modeline,
       this means that the TODO task was created and it was created on the
       file '.notes' on our user home directory.

     - If a warning is displayed ignore it and press the 'q' to quit
       the Capture buffer.

     - Now we are going to add a custom template, press C-x 2 to divide the
       frame on two windows.

     - Press C-x o to jump to the lower window.

     - Press C-x C-f and visit the file '~/.emacs.d/init.el' and press RET.

     - Add the following text to it and save it:

       (setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
         "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/org/journal.org")
         "* %?\nEntered on %U\n  %i\n  %a")))

       On the previous configuration we define two templates: A TODO item
       similar to the one we used before, and a Journal item, NOTE that
       here we define that the files must be saved on the files:
       "~/org/gtd.org" and "~/org/journal.org"

     - Close Emacs, open this file again and comeback to this line.

     - Go to the ALPHA heading and press C-c c.

     - Now two templates are shown on the Capture buffer: Tasks and Journal.

     - Type the 'j' key to add a Journal entry.

     - When it shows (on the Capture buffer), type the heading title:
       'Learned capture today' and press C-c C-c, Emacs will ask you if you
       want to create the directory '~/org/', type the 'y' key and press
       RET, the journal entry is saved.

**** ALPHA

*** Attachments

**** Description

     You can attach files to an Org document, the files are located on
     a directory that belongs to the outline node.

     Org can address directories by name, by unique entry ID or by using
     the 'DIR' property.

**** Keybidings

     - C-c C-a => Call the attachments dispatcher.

     
**** Orders

     - Go to the BRAVO heading and press C-c C-a, this will open a buffer
       on the bottom of Emacs, this is the attachments dispatcher interface.
       
     - 

**** BRAVO

     The bravo information.
