#+STARTUP: showall

EMACS ORG-MODE
============================================================================

Hello recruit and welcome to the Air Force where you will learn
to FLY using Org Mode.

* Mission #30: Archiving

** Briefing

   On this mission you will learn how to add information to an archive.

** Mission

*** Archiving:

**** Keybindings

     - C-c C-x C-a => Archive the current entry.
       
     - C-c $ => Archive the current subtree.

**** Orders

     - Go to the ALPHA heading and press C-c C-x C-a, the text
       'subtree archived on
       ~/emacs-bootcamp/03-org/mission-30-archiving.org_archive' is displayed
       on the Modeline.

     - Press C-x C-c to try to exit Emacs, Emacs won't let you and will tell
       you that there is a buffer named 'mission-30-archiving.org_archive'
       with modifications and if you want to save it.

     - Type the 'y' key two times, Emacs will save the archived file and will
       exit, open this file again and get back to this line.

     - The previous action saved the ALPHA tree to an archive file, press
       C-x 2 to divide the frame in two windows.

     - Press C-x o to jump to the lower window.

     - Press C-x C-f and visit the file
       '~/emacs-bootcamp/03-org/mission-30-archiving.org_archive'.

     - The archive is opened and you can see that the ALPHA tree is
       indeed there, put the point over the ALPHA heading and press TAB, this
       will display the keyworkd ':PROPERTIES:'.

     - Put the point on the ':PROPERTIES:' line and press TAB to display
       its contents.

     - Press C-x o to jump back to this buffer.

     - Go to the BRAVO line and press C-c $

     - Press C-x o to jump to the archive buffer.

     - Press M-> to go to the end of the archive buffer, you can see that
       the BRAVO tree is there.

     - Press C-x 0 to show only this buffer.
